### ISSUE TITLE
As a user, I want to set reminders for tasks like watering, fertilizing, and pest control.

### ISSUE THREAD

**Issue by Abdriano95** [joakimolssonn/DWA-AU24-Lab2-Group-11#15]
**User Story:**

As a user, I want to set reminders for tasks like watering, fertilizing, and pest control so that I can keep my crops healthy.

**Tasks:**
- [ ] Create the form for adding farm tasks (watering, fertilizing, pest control)
- [ ] Implement logic to store task reminders in the database
- [ ] Write unit tests to ensure task reminders are stored correctly
