### ISSUE TITLE
As an admin, I want to control access to certain features based on user roles so that only authorized users can perform specific action

### ISSUE THREAD

**Issue by Abdriano95** [joakimolssonn/DWA-AU24-Lab2-Group-11#21]
**User Story:**

As an admin, I want to control access to certain features based on user roles so that only authorized users can perform specific actions.

**Tasks:**
- [ ] Implement role-based or claims-based authorization
- [ ] Restrict access to specific features based on user roles
- [ ] Write tests to verify that unauthorized users cannot access restricted areas
