### ISSUE TITLE
As a user, I want to add details about the crops I’m planting so I can track the types of crops and their planting dates.

### ISSUE THREAD

**Issue by Abdriano95** [joakimolssonn/DWA-AU24-Lab2-Group-11#6]
Task: Create forms and views for entering crop details.
Task: Store crop information in the database.

**Comment by Abdriano95** [comment]
**User Story:**

As a user, I want to enter crop details so that I can track the types of crops and their planting dates.

**Tasks:**
- [ ] Create form for entering crop details (Crop/Create view)
- [ ] Validate input fields for crop creation form
- [ ] Store crop data in the database
- [ ] Write unit tests for the crop creation form and validation
